# --- QMIX 相关参数 ---

# 使用 epsilon 贪心策略作为动作选择器
action_selector: "epsilon_greedy"
epsilon_start: 1.0           # 初始 epsilon 值
epsilon_finish: 0.05         # 最终 epsilon 值
epsilon_anneal_time: 50000   # epsilon 退火时间步数

runner: "episode"            # 运行方式：以 episode 为单位运行环境

buffer_size: 5000            # 回放缓冲区大小

# 每隔一定的 episode 数更新一次目标网络
target_update_interval: 200

# 使用 Q_Learner 进行训练
agent_output_type: "q"       # 智能体输出类型为 Q 值
learner: "q_learner"         # 学习器类型：q_learner
double_q: True               # 是否使用 Double Q-Learning
mixer: "qmix"                # Mixer 类型：qmix，用于融合各智能体的 Q 值
mixing_embed_dim: 32         # Mixer 嵌入层的维度
hypernet_layers: 2           # 超网络的层数
hypernet_embed: 64           # 超网络嵌入层的维度

name: "qmix"                 # 实验名称
